# Generated by Django 4.0.3 on 2022-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=False),
        ),
    ]
