# Generated by Django 4.0.6 on 2022-12-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'serial_action',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('doc_no', models.CharField(default=0, max_length=60)),
                ('status', models.BooleanField(default=True)),
                ('etc', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'sheet',
            },
        ),
        migrations.CreateModel(
            name='StockByWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=20)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sheet')),
            ],
            options={
                'db_table': 'stock_by_warehouse',
            },
        ),
        migrations.CreateModel(
            name='SheetComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('warehouse_code', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sheet')),
            ],
            options={
                'db_table': 'sheet_composition',
            },
        ),
        migrations.CreateModel(
            name='SerialComposeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='stock.serialaction')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='stock.serialaction')),
            ],
            options={
                'db_table': 'serial_compose_record',
            },
        ),
        migrations.AddField(
            model_name='serialaction',
            name='compose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compose', to='stock.sheet'),
        ),
        migrations.AddField(
            model_name='serialaction',
            name='create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create', to='stock.sheet'),
        ),
        migrations.AddField(
            model_name='serialaction',
            name='outbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound', to='stock.sheet'),
        ),
        migrations.AddField(
            model_name='serialaction',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='stock.sheet'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10)),
                ('inbound_price', models.IntegerField(default=0)),
                ('outbound_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'inventory_price',
            },
        ),
    ]
