# Generated by Django 4.0.6 on 2022-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
