# Generated by Django 4.0.6 on 2022-11-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productprice',
            table='Inventory_price',
        ),
    ]
