# Generated by Django 4.0.6 on 2022-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbound',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
