# Generated by Django 4.0.6 on 2022-12-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_sheet_created_at_alter_sheet_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='doc_no',
        ),
    ]
