# Generated by Django 4.0.6 on 2022-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_productinbound_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='company_code',
            field=models.CharField(default='AA', max_length=10),
        ),
    ]
