# Generated by Django 4.0.6 on 2023-01-02 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('companies', '0001_initial'),
        ('stock', '0002_remove_sheet_company_sheet_company_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPrice',
            new_name='ProductPrice2',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 14, 0, 49, 308593)),
        ),
    ]
