# Generated by Django 4.0.6 on 2022-11-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_productprice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productprice',
            table='inventory_price',
        ),
        migrations.AlterModelTable(
            name='totalproductquantity',
            table='inventory_quantity',
        ),
    ]
