# Generated by Django 4.0.6 on 2022-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_productprice_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='company_code',
            field=models.CharField(max_length=10),
        ),
    ]
