# Generated by Django 4.0.6 on 2022-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_productprice_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysheet',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
