# Generated by Django 4.0.6 on 2023-01-05 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_serialcode_status_alter_sheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 18, 48, 4, 145608)),
        ),
    ]
