# Generated by Django 4.0.6 on 2023-01-02 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('companies', '0001_initial'),
        ('stock', '0003_rename_productprice_productprice2_alter_sheet_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPrice2',
            new_name='ProductPrice',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 14, 1, 9, 450857)),
        ),
    ]
