# Generated by Django 4.0.6 on 2022-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_sheet_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='company_code',
            field=models.CharField(max_length=20),
        ),
    ]
