# Generated by Django 4.0.6 on 2023-01-06 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('stock', '0004_alter_sheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialcodevalue',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serialcodevalue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 6, 16, 4, 7, 891692)),
        ),
    ]
