# Generated by Django 4.0.6 on 2022-12-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_code'),
        ('stock', '0005_alter_sheet_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityByWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=20)),
                ('total_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'quantity_by_warehouse',
            },
        ),
    ]
