# Generated by Django 4.0.6 on 2023-01-06 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_serialcodevalue_date_serialcodevalue_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='related_sheet',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 6, 18, 7, 45, 230233)),
        ),
    ]
