# Generated by Django 4.0.6 on 2022-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_inventorysheetlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysheetlog',
            name='after_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysheetlog',
            name='before_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
