# Generated by Django 4.0.6 on 2023-01-06 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_sheet_related_sheet_alter_sheet_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='related_sheet',
            new_name='related_sheet_id',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 6, 18, 26, 24, 542190)),
        ),
    ]
