# Generated by Django 4.0.6 on 2022-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_quantitybywarehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialaction',
            name='compose',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='serialaction',
            name='create',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='serialaction',
            name='outbound',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='serialaction',
            name='transfer',
            field=models.CharField(max_length=20),
        ),
    ]
