# Generated by Django 4.0.6 on 2023-01-11 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_sheet_company_alter_sheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='document_num',
            field=models.CharField(default='fix', max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 13, 30, 0, 277639)),
        ),
    ]
