# Generated by Django 4.0.6 on 2022-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_inventorysheetlog_after_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysheet',
            name='doc_no',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
