# Generated by Django 4.0.6 on 2023-01-09 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_rename_related_sheet_sheet_related_sheet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialcodevalue',
            name='contents',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 9, 15, 17, 41, 271034)),
        ),
        migrations.AlterModelTable(
            name='serialcodevalue',
            table='serial_code_value',
        ),
    ]
