# Generated by Django 4.0.6 on 2022-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_serialaction_compose_alter_serialaction_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcomposition',
            name='etc',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
