# Generated by Django 4.0.6 on 2022-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_sheetcomposition_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetcomposition',
            name='etc',
            field=models.CharField(max_length=300),
        ),
    ]
