# Generated by Django 4.0.6 on 2022-12-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_barcode'),
        ('stock', '0009_alter_sheetcomposition_etc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialaction',
            name='compose',
        ),
        migrations.RemoveField(
            model_name='serialaction',
            name='create',
        ),
        migrations.RemoveField(
            model_name='serialaction',
            name='outbound',
        ),
        migrations.RemoveField(
            model_name='serialaction',
            name='transfer',
        ),
        migrations.AddField(
            model_name='serialaction',
            name='actions',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='serialaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
