# Generated by Django 4.0.6 on 2022-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_inventorysheet_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysheet',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
