# Generated by Django 4.0.6 on 2023-01-11 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('stock', '0010_alter_sheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 16, 18, 59, 866847)),
        ),
    ]
