# Generated by Django 4.0.6 on 2022-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_inventorysheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysheet',
            name='date',
            field=models.DateField(),
        ),
    ]
