# Generated by Django 4.0.6 on 2022-12-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_serialaction_actions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialInSheetComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(max_length=100)),
                ('sheet_composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sheetcomposition')),
            ],
            options={
                'db_table': 'serial_in_sheet_composition',
            },
        ),
    ]
