# Generated by Django 4.0.6 on 2023-01-12 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('stock', '0012_alter_sheet_date_alter_sheet_related_sheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 17, 2, 25, 919151)),
        ),
        migrations.AlterField(
            model_name='sheetlog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
