# Generated by Django 4.0.6 on 2023-01-12 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_sheet_date_alter_sheetlog_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 17, 47, 49, 714980)),
        ),
    ]
