# Generated by Django 4.0.6 on 2022-12-28 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_sheetlog_alter_sheet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 10, 51, 43, 605450)),
        ),
    ]
