# Generated by Django 4.0.6 on 2022-12-28 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_sheet_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'serial_codes',
            },
        ),
        migrations.CreateModel(
            name='SerialCodeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'serial_code_titles',
            },
        ),
        migrations.CreateModel(
            name='SerialCodeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.IntegerField()),
                ('contents', models.CharField(max_length=200)),
                ('serial_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_code_value', to='stock.serialcode')),
            ],
            options={
                'db_table': 'serial_code_values',
            },
        ),
        migrations.RemoveField(
            model_name='serialcomposerecord',
            name='compose',
        ),
        migrations.RemoveField(
            model_name='serialcomposerecord',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='serialinsheetcomposition',
            name='sheet_composition',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 15, 16, 41, 334375)),
        ),
        migrations.DeleteModel(
            name='SerialAction',
        ),
        migrations.DeleteModel(
            name='SerialComposeRecord',
        ),
        migrations.DeleteModel(
            name='SerialInSheetComposition',
        ),
    ]
