# Generated by Django 4.0.6 on 2023-01-12 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_sheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movingaveragemethod',
            name='custom_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 17, 55, 50, 969141)),
        ),
    ]
