# Generated by Django 4.0.6 on 2023-01-16 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_movingaveragemethod_custom_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 11, 42, 4, 594389)),
        ),
        migrations.CreateModel(
            name='SetSerialCodeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_serial_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_serial_code', to='stock.serialcode')),
                ('set_serial_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.serialcode')),
            ],
            options={
                'db_table': 'set_serial_code_component',
            },
        ),
    ]
