# Generated by Django 4.0.6 on 2022-12-28 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_serialcode_serialcodetitle_serialcodevalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialcodevalue',
            name='title_id',
        ),
        migrations.AddField(
            model_name='serialcodevalue',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.serialcodetitle'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 17, 51, 31, 391060)),
        ),
    ]
