# Generated by Django 4.0.6 on 2023-01-17 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_sheet_date_setserialcodecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 15, 35, 59, 160515)),
        ),
        migrations.AlterField(
            model_name='sheetcomposition',
            name='warehouse_code',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
