# Generated by Django 4.1.5 on 2023-02-10 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_sheet_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 10, 22, 35, 31, 714760)),
        ),
        migrations.AddField(
            model_name='sheetlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 22, 35, 31, 714819)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 10, 22, 35, 31, 712069)),
        ),
    ]
