# Generated by Django 4.0.6 on 2022-12-29 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productetcdesc_table_and_more'),
        ('stock', '0017_alter_serialcodevalue_title_alter_sheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 15, 9, 38, 336774)),
        ),
        migrations.CreateModel(
            name='MovingAverageMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_price', models.IntegerField()),
                ('custom_price', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'moving_average_method',
            },
        ),
    ]
