# Generated by Django 4.0.6 on 2022-12-29 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_sheet_date_movingaveragemethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movingaveragemethod',
            name='custom_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 15, 19, 47, 162890)),
        ),
    ]
