# Generated by Django 4.0.6 on 2023-01-02 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_customtitle_customvalue_delete_companyetcdesc_and_more'),
        ('stock', '0019_alter_movingaveragemethod_custom_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='sheetlog',
            name='company_code',
        ),
        migrations.AddField(
            model_name='sheet',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='sheetlog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 10, 18, 37, 232360)),
        ),
    ]
