# Generated by Django 4.0.6 on 2023-01-02 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_customtitle_customvalue_delete_companyetcdesc_and_more'),
        ('stock', '0022_remove_productprice_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 10, 23, 53, 913177)),
        ),
    ]
