<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-11-24 13:49
=======
# Generated by Django 4.0.6 on 2022-11-24 13:31
>>>>>>> 2f5cc696705d7a7a0d2fb184ae68d2d9ce9378e0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('represent', models.CharField(max_length=30)),
                ('biz_no', models.CharField(max_length=30)),
                ('biz_type', models.CharField(max_length=100)),
                ('biz_item', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address_main', models.CharField(max_length=120)),
                ('address_desc', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyEtcTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'company_etc_title',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'db_table': 'company_phonebook',
            },
        ),
        migrations.CreateModel(
            name='CompanyEtcDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=700)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('company_etc_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyetctitle')),
            ],
            options={
                'db_table': 'company_etc_desc',
            },
        ),
    ]
