# Generated by Django 4.0.6 on 2022-12-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'company_custom_title',
            },
        ),
        migrations.CreateModel(
            name='CustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('custom_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.customtitle')),
            ],
            options={
                'db_table': 'company_custom_value',
            },
        ),
        migrations.DeleteModel(
            name='CompanyEtcDesc',
        ),
        migrations.DeleteModel(
            name='CompanyEtcTitle',
        ),
    ]
