# Generated by Django 4.0.6 on 2022-11-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyetcdesc',
            name='comp_code',
        ),
        migrations.RemoveField(
            model_name='companyphonebook',
            name='comp_code',
        ),
        migrations.AddField(
            model_name='companyetcdesc',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyphonebook',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
