# Generated by Django 4.0.6 on 2022-11-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationproduct',
            name='quantity',
        ),
    ]
