# Generated by Django 4.0.6 on 2022-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='main',
            field=models.BooleanField(default=0),
        ),
    ]
