# Generated by Django 4.0.6 on 2022-11-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=30)),
                ('biz_no', models.CharField(max_length=30)),
                ('biz_type', models.CharField(max_length=100)),
                ('biz_item', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address_main', models.CharField(max_length=120)),
                ('address_desc', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_code', models.CharField(max_length=10)),
                ('no', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('contents', models.CharField(max_length=700)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'company_etc',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'company_phonebook',
            },
        ),
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=5)),
                ('etc', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'inbound_order',
            },
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=5)),
                ('etc', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'outbound_order',
            },
        ),
        migrations.CreateModel(
            name='ProductD1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('safe_quantity', models.IntegerField()),
                ('search_word', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'productD1',
            },
        ),
        migrations.CreateModel(
            name='ProductD2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('safe_quantity', models.IntegerField()),
                ('search_word', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productD2',
            },
        ),
        migrations.CreateModel(
            name='ProductD2Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d2_code', models.CharField(max_length=10)),
                ('com_code', models.CharField(max_length=10)),
                ('com_quan', models.IntegerField()),
            ],
            options={
                'db_table': 'productD2_composition',
            },
        ),
        migrations.CreateModel(
            name='ProductD3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('safe_quantity', models.IntegerField()),
                ('search_word', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productD3',
            },
        ),
        migrations.CreateModel(
            name='ProductD3Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d3_code', models.CharField(max_length=10)),
                ('com_code', models.CharField(max_length=10)),
                ('com_quan', models.IntegerField()),
            ],
            options={
                'db_table': 'productD3_composition',
            },
        ),
        migrations.CreateModel(
            name='ProductEtc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('no', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('contents', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'product_etc',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'product_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('barcode', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_his',
            },
        ),
        migrations.CreateModel(
            name='OutboundQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=40)),
                ('outbound_price', models.BigIntegerField()),
                ('outbound_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outboundorder')),
            ],
            options={
                'db_table': 'outbound_quantity',
            },
        ),
        migrations.CreateModel(
            name='InboundQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('inbound_price', models.BigIntegerField()),
                ('inbound_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.inboundorder')),
            ],
            options={
                'db_table': 'inbound_quantity',
            },
        ),
    ]
