# Generated by Django 4.0.6 on 2022-11-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_set', models.BooleanField(default=False)),
                ('company_code', models.CharField(max_length=10)),
                ('productgroup_code', models.CharField(max_length=10)),
                ('product_num', models.CharField(max_length=10)),
                ('safe_quantity', models.IntegerField(default=0)),
                ('keyword', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('warehouse_code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductEtcTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_etc_title',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=3000)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductEtcDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=700)),
                ('etc_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productetctitle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_etc_desc',
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('composition_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_product', to='products.product')),
                ('set_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_composition',
            },
        ),
    ]
