# Generated by Django 4.0.3 on 2022-10-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=120)),
                ('managers', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('mobilephone', models.CharField(max_length=13)),
                ('manage_tag', models.CharField(max_length=30)),
                ('etc', models.CharField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=5)),
                ('etc', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'inbound_order',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_status', models.IntegerField()),
                ('serial_code', models.CharField(max_length=10)),
                ('price', models.BigIntegerField()),
                ('barcode', models.CharField(max_length=20)),
                ('etc', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_his',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('safe_quantity', models.IntegerField()),
                ('search_word', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_info',
            },
        ),
        migrations.CreateModel(
            name='InboundQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(max_length=10)),
                ('inbound_price', models.BigIntegerField()),
                ('inbound_quntity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.inboundorder')),
            ],
            options={
                'db_table': 'inbound_quantity',
            },
        ),
    ]
