# Generated by Django 4.0.6 on 2022-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productd1',
            name='safe_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
