# Generated by Django 4.0.6 on 2023-01-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productgroup_code',
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productgroup'),
        ),
    ]
