# Generated by Django 4.0.6 on 2022-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.IntegerField(default=1),
        ),
    ]
