# Generated by Django 4.0.6 on 2022-11-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEtcDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('contents', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'product_etc_desc',
            },
        ),
        migrations.CreateModel(
            name='ProductEtcTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_etc_title',
            },
        ),
        migrations.DeleteModel(
            name='ProductEtc',
        ),
        migrations.AddField(
            model_name='productetcdesc',
            name='product_etc_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productetctitle'),
        ),
    ]
