# Generated by Django 4.0.3 on 2022-10-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
