# Generated by Django 4.0.6 on 2023-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_serial',
            field=models.BooleanField(default=False),
        ),
    ]
