# Generated by Django 4.0.6 on 2022-11-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
    ]
