# Generated by Django 4.0.6 on 2022-11-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyetc',
            name='no',
        ),
    ]
