# Generated by Django 4.0.6 on 2022-11-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productd1',
            name='company_code',
        ),
        migrations.CreateModel(
            name='ProductD1Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10)),
                ('productD1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd1')),
            ],
        ),
    ]
