# Generated by Django 4.0.6 on 2022-10-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='resent_IB_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='resent_OB_price',
            field=models.IntegerField(default=1),
        ),
    ]
