# Generated by Django 4.0.6 on 2022-11-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productd1_safe_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productd1',
            name='quantity',
        ),
    ]
