# Generated by Django 4.0.6 on 2022-11-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productd1_company_code_productd1company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductD2Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductD3Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductD3Composition1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_quan', models.IntegerField()),
                ('productD1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd1')),
            ],
            options={
                'db_table': 'productD3_composition_D1',
            },
        ),
        migrations.CreateModel(
            name='ProductD3Composition2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_quan', models.IntegerField()),
            ],
            options={
                'db_table': 'productD3_composition_D2',
            },
        ),
        migrations.RemoveField(
            model_name='productd2',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='productd3',
            name='company_code',
        ),
        migrations.DeleteModel(
            name='ProductD3Composition',
        ),
        migrations.AddField(
            model_name='productd3composition2',
            name='productD2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd2'),
        ),
        migrations.AddField(
            model_name='productd3composition2',
            name='productD3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd3'),
        ),
        migrations.AddField(
            model_name='productd3composition1',
            name='productD3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd3'),
        ),
        migrations.AddField(
            model_name='productd3company',
            name='productD3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd3'),
        ),
        migrations.AddField(
            model_name='productd2company',
            name='productD2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd2'),
        ),
    ]
