# Generated by Django 4.0.6 on 2022-11-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productd2company_productd3company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductD1EtcDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=700)),
                ('productD1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd1')),
            ],
            options={
                'db_table': 'productD1_etc_desc',
            },
        ),
        migrations.CreateModel(
            name='ProductD2EtcDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=700)),
                ('productD2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd2')),
            ],
            options={
                'db_table': 'productD2_etc_desc',
            },
        ),
        migrations.CreateModel(
            name='ProductD3EtcDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=700)),
                ('productD3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productd3')),
            ],
            options={
                'db_table': 'productD3_etc_desc',
            },
        ),
        migrations.RemoveField(
            model_name='inboundorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inboundquantity',
            name='inbound_order',
        ),
        migrations.RemoveField(
            model_name='outboundorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outboundquantity',
            name='outbound_order',
        ),
        migrations.RemoveField(
            model_name='productetcdesc',
            name='product_etc_title',
        ),
        migrations.DeleteModel(
            name='ProductHis',
        ),
        migrations.AlterField(
            model_name='productetctitle',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='InboundOrder',
        ),
        migrations.DeleteModel(
            name='InboundQuantity',
        ),
        migrations.DeleteModel(
            name='OutboundOrder',
        ),
        migrations.DeleteModel(
            name='OutboundQuantity',
        ),
        migrations.DeleteModel(
            name='ProductEtcDesc',
        ),
        migrations.AddField(
            model_name='productd3etcdesc',
            name='product_etc_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productetctitle'),
        ),
        migrations.AddField(
            model_name='productd2etcdesc',
            name='product_etc_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productetctitle'),
        ),
        migrations.AddField(
            model_name='productd1etcdesc',
            name='product_etc_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productetctitle'),
        ),
    ]
