# Generated by Django 4.0.6 on 2022-11-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productd1_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productd2',
            old_name='productgroup_num',
            new_name='company_code',
        ),
        migrations.RemoveField(
            model_name='productd2',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productd2',
            name='location',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AddField(
            model_name='productd2',
            name='product_num',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='productd2',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productd2',
            name='warehouse_code',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='productd2',
            name='safe_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductD2Company',
        ),
    ]
