# Generated by Django 4.0.6 on 2023-01-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0003_alter_product_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_code',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
