# Generated by Django 4.0.6 on 2022-10-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productinfo_resent_ib_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='resent_IB_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='resent_OB_price',
            field=models.IntegerField(),
        ),
    ]
