# Generated by Django 4.0.6 on 2022-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_model_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='etc',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
