# Generated by Django 4.0.6 on 2022-11-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productd1etcdesc_productd2etcdesc_productd3etcdesc_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productd1company',
            table='productD1_company',
        ),
        migrations.AlterModelTable(
            name='productd2company',
            table='productD2_company',
        ),
        migrations.AlterModelTable(
            name='productd3company',
            table='productD3_company',
        ),
    ]
