# Generated by Django 4.0.6 on 2022-11-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_productgroup_num_productd2_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productd2',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productd2',
            name='product_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productd2',
            name='warehouse_code',
            field=models.CharField(max_length=10),
        ),
    ]
