# Generated by Django 4.0.6 on 2022-10-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
        ('products', '0004_alter_productinfo_resent_ib_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=5)),
                ('etc', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'outbound_order',
            },
        ),
        migrations.CreateModel(
            name='OutboundQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=40)),
                ('outbound_price', models.BigIntegerField()),
                ('outbound_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbound_oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outboundorder')),
            ],
            options={
                'db_table': 'outbound_quantity',
            },
        ),
    ]
