# Generated by Django 4.0.6 on 2022-11-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_companyetcdesc_companyetctitle_delete_companyetc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owner',
            new_name='represent',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
