# Generated by Django 4.0.6 on 2022-10-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_outboundorder_outboundquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outboundquantity',
            old_name='outbound_oder',
            new_name='outbound_order',
        ),
        migrations.RenameField(
            model_name='outboundquantity',
            old_name='barcode',
            new_name='serial_code',
        ),
        migrations.CreateModel(
            name='OutboundBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outboundorder')),
            ],
            options={
                'db_table': 'outbound_barcode',
            },
        ),
    ]
