# Generated by Django 4.0.6 on 2022-11-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_owner_company_represent_company_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
