# Generated by Django 4.0.6 on 2022-10-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_quantity_productquantity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productquantity',
            table='product_quantity',
        ),
    ]
