# Generated by Django 4.0.6 on 2022-10-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_outbound_oder_outboundquantity_outbound_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboundquantity',
            old_name='serial_code',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='outboundquantity',
            old_name='serial_code',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='producthis',
            old_name='serial_code',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='serial_code',
            new_name='product_code',
        ),
    ]
