# Generated by Django 4.0.6 on 2022-10-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productquantity_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='serch_word',
            new_name='search_word',
        ),
    ]
