# Generated by Django 4.0.6 on 2022-11-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_company_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='companyetcdesc',
            name='company_etc_title',
        ),
        migrations.DeleteModel(
            name='CompanyPhonebook',
        ),
        migrations.DeleteModel(
            name='CompanyEtcDesc',
        ),
        migrations.DeleteModel(
            name='CompanyEtcTitle',
        ),
    ]
