# Generated by Django 4.0.3 on 2022-10-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_serial_code_inboundquantity_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInboundPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('company_code', models.CharField(max_length=5)),
                ('resent_price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'company_inbound_price',
            },
        ),
        migrations.CreateModel(
            name='CompanyOutboundPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('company_code', models.CharField(max_length=5)),
                ('resent_price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'company_outbound_price',
            },
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='resent_IB_price',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='resent_OB_price',
        ),
    ]
