# Generated by Django 4.0.6 on 2022-10-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_serch_word_product_search_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='product',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='product_serial_code',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
