# Generated by Django 4.0.3 on 2022-10-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_companyinboundprice_companyoutboundprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('etc', models.CharField(blank=True, max_length=3000)),
            ],
            options={
                'db_table': 'bom',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('etc', models.CharField(blank=True, max_length=3000)),
            ],
            options={
                'db_table': 'set',
            },
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.set')),
            ],
            options={
                'db_table': 'set_product',
            },
        ),
        migrations.CreateModel(
            name='OutboundSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outboundorder')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.set')),
            ],
            options={
                'db_table': 'outbound_set',
            },
        ),
        migrations.CreateModel(
            name='OutboundBom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bom')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outboundorder')),
            ],
            options={
                'db_table': 'outbound_bom',
            },
        ),
        migrations.CreateModel(
            name='BomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('BOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bom')),
            ],
            options={
                'db_table': 'bom_product',
            },
        ),
    ]
