# Generated by Django 4.0.6 on 2022-10-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productquantity_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='product_serial_code',
            field=models.CharField(max_length=30),
        ),
    ]
