# Generated by Django 4.0.3 on 2022-10-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
        ('products', '0009_alter_productquantity_product_serial_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateWarehousingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etc', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'inbound_order',
            },
        ),
        migrations.CreateModel(
            name='InboundQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_price', models.BigIntegerField()),
                ('inbound_quntity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.inboundorder')),
            ],
            options={
                'db_table': 'inbound_quantity',
            },
        ),
        migrations.CreateModel(
            name='ProductHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('barcode', models.CharField(max_length=20)),
                ('etc', models.CharField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_his',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('safe_quantity', models.IntegerField()),
                ('search_word', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_info',
            },
        ),
        migrations.CreateModel(
            name='SerialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.IntegerField()),
                ('created_code', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.company')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup')),
            ],
            options={
                'db_table': 'serial_code',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_status',
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.RemoveField(
            model_name='warehousingorder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='warehousingorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehousingorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='WarehousingOrder',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='serial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.serialcode'),
        ),
        migrations.AddField(
            model_name='producthis',
            name='serial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.serialcode'),
        ),
        migrations.AddField(
            model_name='producthis',
            name='use_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.usestatus'),
        ),
        migrations.AddField(
            model_name='inboundquantity',
            name='serial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.serialcode'),
        ),
    ]
