# Generated by Django 4.0.3 on 2022-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_bom_set_setproduct_outboundset_outboundbom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setproduct',
            name='product_price',
        ),
        migrations.AddField(
            model_name='set',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
