# Generated by Django 4.0.3 on 2022-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_setproduct_product_price_set_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='price',
            field=models.IntegerField(),
        ),
    ]
