# Generated by Django 4.0.3 on 2022-10-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_createwarehousingorder_inboundorder_inboundquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundorder',
            name='company',
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='company_code',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='inboundquantity',
            name='serial_code',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='producthis',
            name='serial_code',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='producthis',
            name='use_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='serial_code',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.DeleteModel(
            name='SerialCode',
        ),
        migrations.DeleteModel(
            name='UseStatus',
        ),
    ]
