# Generated by Django 4.0.3 on 2022-10-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_set_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundSetQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_code', models.CharField(default=0, max_length=10)),
                ('quantity', models.IntegerField()),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outboundorder')),
            ],
            options={
                'db_table': 'outbound_set_info',
            },
        ),
        migrations.CreateModel(
            name='SetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_code', models.CharField(default=0, max_length=10)),
                ('quantity', models.IntegerField()),
                ('safe_quantity', models.IntegerField()),
                ('search_word', models.CharField(default=0, max_length=150)),
                ('name', models.CharField(default=0, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'set_info',
            },
        ),
        migrations.RemoveField(
            model_name='setproduct',
            name='set',
        ),
        migrations.AddField(
            model_name='setproduct',
            name='set_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='product_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterModelTable(
            name='setproduct',
            table='set_info_product',
        ),
        migrations.DeleteModel(
            name='OutboundSet',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
