# Generated by Django 4.0.3 on 2022-10-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_inboundorder_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundorder',
            name='company_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='inboundquantity',
            name='serial_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='producthis',
            name='serial_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='serial_code',
            field=models.CharField(max_length=10),
        ),
    ]
