# Generated by Django 4.0.3 on 2022-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_outboundsetquantity_setinfo_remove_setproduct_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundsetquantity',
            name='set_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='search_word',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='set_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='product_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='setproduct',
            name='set_code',
            field=models.CharField(max_length=10),
        ),
    ]
